export const langArr = {
  "title": {
    "ru" : "Главная",
    "en" : "Home",
    "ua" : "Головна"
  },
  "nav": {
    "home" : {
      "ru" : "Главная",
      "en" : "Home",
      "ua" : "Головна"
    }
  }
}

export const i18Obj = {
  en: {
    home: 'Home',
    services: "Services",
    about: "About",
    product: "Product",
    "sign-in": "Sign In",
    "sign-up": "Sign Up",
    "banner-title" : "The Design Thinking superpowers",
    "banner-text" : "Tools, tutorials, design and innovation experts, all in one place! The most intuitive way to imagine your next user experience.",
    "get-started" : "Get Started",
    "watch-video" : "watch the video",
    "tools-title" : "We design tools to unveil your superpowers",
    "first-click" : "First click tests",
    "first-click-text" : "While most people enjoy casino gambling",
    "design" : "Design surveys",
    "design-text" : "Sports betting, lottery and bingo playing for the fun",
    "tests": "Preference tests",
    "tests-text": "The Myspace page defines the individual.",
    "five" : "Five second tests",
    "five-text" : "Personal choices and the overall personality of the person.",
    "tools-link": "Sign Up Now",
    "strategy-title" : "Marketing Strategies",
    "strategy-subtitle" : "Join 40,000+ other marketers and get proven strategies on email marketing",
    "All": "All",
    "Art": "Art",
    "Culture": "Culture",
    "Design": "Design",
    "About-Us-Title": "About Us",
    "About-Us-Text" : "Your About Us page is vital. It’s often the first stop in any user’s journey through a website or blog. It also shouldn’t be their last, because first impressions count online just as much as they do in the real world. If your visitors aren’t impressed, you can expect them to leave without reading your awesome content or completing a conversion action (e.g., signing up for your newsletter, making a purchase).",
    "About-Us-name-1": "Kathy Rosenberg",
    "About-Us-position-1" : "Kathy Rosenberg",
    "About-Us-name-2": "Alexandra Boyarskaya",
    "About-Us-position-2" : "Support Marketing Specialist",
    "About-Us-name-3": "Melani Amini",
    "About-Us-position-3" : "Photographer",
    "Contact-Us-title" : "Contact Us",
    "Contact-Us-text" : "Your About Us page is vital. It’s often the first stop in any user’s journey through a website or blog. It also shouldn’t be their last, because first impressions count online just as much as they do in the real world. If your visitors aren’t impressed, you can expect them to leave without reading your awesome content or completing a conversion action (e.g., signing up for your newsletter, making a purchase).",
    "input-name" : "Your name",
    "input-mail" : "Your mail",
    "input-ask" : "What do you want to ask?",
    "input-send" : "Send",
    "Quick-Links" : "Quick-Links",
    "Legal Stuff" : "Legal Stuff",
    "Blog" : "Blog",
    "Contact" : "Contact",
    "FAQ" : "FAQ",
    "Disclaimer" : "Disclaimer",
    "Financing" : "Financing",
    "Privacy Policy" : "Privacy Policy",
    "Terms of Service" : "Terms of Service",
  },
  ua: {
    home: 'Головна',
    services: "Сервіси",
    about: "Про нас",
    product: "Продукт",
    "sign-in": "Ввійти",
    "sign-up": "Вийти",
    "banner-title" : "Суперздібності дизайнерського мислення",
    "banner-text" : "Інструменти, навчальні посібники, експерти з дизайну та інновацій – все в одному місці! Найбільш інтуїтивно зрозумілий спосіб уявити ваш наступний досвід користувача.",
    "get-started" : "Розпочати",
    "watch-video" : "Подивіться відео",
    "tools-title" : "Ми розробляємо інструменти, щоб розкрити ваші надздібності",
    "first-click" : "Тести з першого натискання",
    "first-click-text" : "Хоча більшість людей люблять азартні ігри в казино",
    "design" : "Проектні обстеження",
    "design-text" : "Ставки на спорт, лотереї та бінго для розваги",
    "tests": "Тесты на перевагу",
    "tests-text": "Сторінка Myspace визначає особу.",
    "five" : "Пʼяти секундні тести",
    "five-text" : "Особистий вибір і загальна особистість людини.",
    "tools-link": "Ввійти зараз",
    "strategy-title" : "Маркетингові стратегії",
    "strategy-subtitle" : "Приєднуйтесь до понад 40 000 інших маркетологів і отримайте перевірені стратегії маркетингу електронною поштою",
    "All": "Всі",
    "Art": "Мистецтво",
    "Culture": "Культура",
    "Design": "Дизайн",
    "About-Us-Title": "Про нас",
    "About-Us-Text" : "Наша сторінка «Про нас» є життєво важливою. Часто це перша зупинка в подорожі користувача веб-сайтом або блогом. Це також не повинно бути останнім, тому що перше враження в Інтернеті враховується так само, як і в реальному світі. Якщо ваші відвідувачі не вражені, ви можете очікувати, що вони підуть, не прочитавши ваш чудовий вміст або не виконавши дії конверсії (наприклад, підписавшись на ваш інформаційний бюлетень, не зробивши покупку).",
    "About-Us-name-1": "Кеті Розенберг",
    "About-Us-position-1" : "Менеджер по продукції",
    "About-Us-name-2": "Олександра Боярська",
    "About-Us-position-2" : "Спеціаліст з маркетингу",
    "About-Us-name-3": "Мелані Аміні",
    "About-Us-position-3" : "Фотограф",
    "Contact-Us-title" : "Контакти",
    "Contact-Us-text" : "Ваша сторінка «Про нас» є життєво важливою. Часто це перша зупинка в подорожі користувача веб-сайтом або блогом. Це також не повинно бути останнім, тому що перше враження в Інтернеті враховується так само, як і в реальному світі. Якщо ваші відвідувачі не вражені, ви можете очікувати, що вони підуть, не прочитавши ваш чудовий вміст або не виконавши дії конверсії (наприклад, підписавшись на ваш інформаційний бюлетень, не зробивши покупку).",
    "input-name" : "Ваше імʼя",
    "input-mail" : "Ваш емейл",
    "input-ask" : "Що ви хочете запитати?",
    "input-send" : "Відправити",
    "Quick-Links" : "Швидкі посилання",
    "Legal Stuff" : "Юридичні матеріали",
    "Blog" : "Блог",
    "Contact" : "Контакти",
    "FAQ" : "Часті запитання?",
    "Disclaimer" : "Відповідальність",
    "Financing" : "Фінансування",
    "Privacy Policy" : "Політика конфеденційності",
    "Terms of Service" : "Правила сервісу",
  }
}